name: Docker Image CI for GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v4.1.0
      - name: Build and push the Docker image
        uses: actions/checkout@v4
        run: |
          docker login --username xenhat --password-stdin ${{ secrets.GH_PAT }} ghcr.io
          docker build . --file Dockerfile --tag dalamud-repo-image:latest
          docker push ghcr.io/xenhat/dalamud-repo-image:latest
